### ISSUE TITLE
Crashes when pasting grid onto powered grid

### ISSUE THREAD

**Issue by 3x3y3z3t** [3x3y3z3t/AtmoHydroPower#2]
### Description
Crashes when pasting grid with Atmo Hydro Thruster onto powered grid.

### To Reproduce
Steps to reproduce the behavior (not always reproducible):
1. Create a grid with thruster.
2. Copy and Paste that grid onto an existing powered grid.
3. Game crash.

### Additional context
SE Log:
```
2022-08-09 04:17:59.134 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at AtmoHydroPower.AtmoHydroPower_GameLogic.UpdateOnceBeforeFrame()
   at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateOnceBeforeFrame(Boolean entityUpdate)
   at VRage.Game.Entity.MyGameLogic.UpdateOnceBeforeFrame()
   at VRage.Game.Entity.MyGameLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by 3x3y3z3t** [comment]
Fixed with d2c56cd0a36a39d9336836e755baba0f500cda9d.
